import Providers from '@/providers/Providers'
import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import GlobalToasts from '@/app/_components/GlobalToasts'

const poppins = Poppins({
  subsets: ['devanagari'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
})

export const metadata: Metadata = {
  title: 'Real time chat',
  description: 'Generated by create next app'
}

interface Props {
  children: React.ReactNode
}

export default function RootLayout({ children }: Props) {
  return (
    <html lang='en'>
      <body className={poppins.className}>
        <Providers>
          <GlobalToasts />
          {children}
        </Providers>
      </body>
    </html>
  )
}
